import { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  es: {
    nav: {
      home: 'Inicio',
      login: 'Iniciar sesión',
      dashboard: 'Dashboard',
      reservations: 'Reservas',
      users: 'Usuarios',
      reserve: 'Reservar',
      myReservations: 'Mis reservas',
      profile: 'Perfil',
      logout: 'Salir',
      adminBadge: 'Admin',
      clientBadge: 'Cliente',
      brandSubtitle: 'Hotel Boutique & Restaurant',
      language: 'Idioma',
      activities: 'Actividades',
    },
    activities: {
      eyebrow: 'EXPERIENCIAS & CURSOS',
      title: 'Actividades & Cursos del Hotel',
      subtitle: 'Enriquece tu estancia con deportes recreativos, spa de bienestar y cursos exclusivos de manualidades dirigidos por instructores certificados.',
      costNote: 'Costo adicional a la reserva de la habitación',
      quotaNote: 'Cupos limitados por sesión',
      whatsappNote: 'Contacto directo con la persona encargada',
      searchPlaceholder: 'Buscar actividad, curso o instructor...',
      itemsFound: 'experiencias con cupos disponibles',
      perPerson: 'persona',
      duration: 'Duración',
      schedule: 'Horario',
      slots: 'Cupos',
      slotsLeft: 'disponibles',
      slotsTotal: 'totales',
      inChargeLabel: 'Persona encargada',
      contactWhatsApp: 'Reservar con encargado',
      noResultsTitle: 'No se encontraron actividades',
      noResultsDesc: 'Intenta con otro término o selecciona otra categoría.',
      viewAllBtn: 'Ver todas las experiencias',
      exclusiveGuests: 'BENEFICIO EXCLUSIVO',
      calloutTitle: '¿Hospedado en ReservaPro?',
      calloutDesc: 'Todos los cargos de actividades y talleres pueden cargarse a la cuenta de tu habitación.',
      viewCatalog: 'Ver actividades y cursos',
    },
    home: {
      eyebrow: 'Exclusividad & Alta Cocina',
      heroTitle: 'Donde el descanso se encuentra con el buen gusto.',
      heroDesc: 'Experiencias boutique inolvidables, habitaciones de lujo y una gastronomía de autor creada para los paladares más exigentes.',
      reserveHotel: 'Reservar Suite',
      reserveDining: 'Mesa Gourmet',
      viewDashboard: 'Ir a mi Dashboard',
      servicesTitle: 'Nuestras Experiencias',
      hotelTitle: 'Suites de Lujo',
      hotelDesc: 'Espacios diseñados con acabados refinados, vistas panorámicas y confort absoluto.',
      restaurantTitle: 'Restaurante de Autor',
      restaurantDesc: 'Menús degustación elaborados con ingredientes locales frescos y maridaje selecto.',
      featuresTitle: 'La Excelencia en Cada Detalle',
      feature1Title: 'Atención Personalizada 24/7',
      feature1Desc: 'Servicio de conserjería dedicado a satisfacer cada uno de sus deseos.',
      feature2Title: 'Gastronomía Premiada',
      feature2Desc: 'Chefs internacionales galardonados con creaciones culinarias únicas.',
      feature3Title: 'Privacidad y Confort',
      feature3Desc: 'Ambientes silenciosos, sofisticados y pensados para un descanso pleno.',
      statsSuites: 'Suites de Lujo',
      statsStars: 'Estrellas Michelin',
      statsSatisfaction: 'Satisfacción',
      statsExperience: 'Años de Tradición',
      quote: '«El lujo verdadero no es la ostentación, sino el arte de hacer inolvidable cada momento.»',
    },
    login: {
      title: 'Iniciar Sesión',
      subtitle: 'Acceda a su cuenta para gestionar sus reservas y servicios exclusivos.',
      email: 'Correo electrónico',
      emailPlaceholder: 'ejemplo@correo.com',
      password: 'Contraseña',
      passwordPlaceholder: '••••••••',
      submitBtn: 'Entrar al portal',
      loadingBtn: 'Verificando...',
      demoTitle: 'Cuentas de demostración disponibles:',
      demoAdmin: 'Administrador (Control total)',
      demoClient: 'Cliente (Gestión de reservas)',
      demoFill: 'Usar credencial',
      errorInvalid: 'Credenciales inválidas. Compruebe su correo y contraseña.',
    },
    dashboard: {
      welcome: 'Bienvenido de nuevo,',
      subtitle: 'Resumen ejecutivo de su estancia y experiencias programadas.',
      adminTitle: 'Panel de Control General',
      adminSubtitle: 'Gestión global de reservas, clientes y métricas del establecimiento.',
      totalReservations: 'Total Reservas',
      hotelReservations: 'Suites / Hotel',
      diningReservations: 'Mesas / Restaurante',
      pendingReservations: 'Pendientes',
      confirmedReservations: 'Confirmadas',
      cancelledReservations: 'Canceladas',
      registeredUsers: 'Usuarios Registrados',
      quickActions: 'Acciones Rápidas',
      newBooking: 'Nueva Reserva',
      viewAllBookings: 'Ver Todas las Reservas',
      manageUsers: 'Gestionar Usuarios',
      recentActivity: 'Actividad Reciente',
      distributionByType: 'Distribución por Servicio',
      statusOverview: 'Estado de Reservas',
      noRecentActivity: 'No hay actividad reciente registrada.',
    },
    reservations: {
      title: 'Mis Reservas',
      subtitle: 'Consulte y administre el itinerario de sus próximas experiencias.',
      adminTitle: 'Administración de Reservas',
      adminSubtitle: 'Supervisión y confirmación de todas las solicitudes de huéspedes.',
      createTitle: 'Crear Nueva Reserva',
      createSubtitle: 'Personalice su estancia o velada en simples pasos.',
      serviceType: 'Tipo de Servicio',
      hotelOption: 'Suite de Hotel',
      restaurantOption: 'Mesa de Restaurante',
      date: 'Fecha',
      time: 'Hora',
      guests: 'Número de Personas',
      notes: 'Peticiones Especiales / Notas',
      notesPlaceholder: 'Alergias, preferencias de habitación, celebración de aniversario...',
      submitCreate: 'Confirmar Solicitud de Reserva',
      creating: 'Procesando reserva...',
      filterAll: 'Todas',
      filterPending: 'Pendientes',
      filterConfirmed: 'Confirmadas',
      filterCancelled: 'Canceladas',
      searchPlaceholder: 'Buscar por nombre, correo o ID...',
      emptyTitle: 'No se encontraron reservas',
      emptyDesc: 'Aún no tiene reservas registradas con estos criterios.',
      makeFirstBooking: 'Hacer una reserva ahora',
      statusPending: 'Pendiente de confirmación',
      statusConfirmed: 'Confirmada',
      statusCancelled: 'Cancelada',
      confirmAction: 'Confirmar',
      cancelAction: 'Cancelar',
      deleteAction: 'Eliminar',
      confirmPrompt: '¿Está seguro de que desea cancelar esta reserva?',
      successCreate: '¡Reserva creada exitosamente!',
      roomType: 'Tipo de Habitación',
      tableType: 'Tipo de Mesa',
    },
    users: {
      title: 'Gestión de Usuarios',
      subtitle: 'Administración de accesos, roles y cuentas del sistema.',
      createUserTitle: 'Registrar Nuevo Usuario',
      name: 'Nombre Completo',
      email: 'Correo Electrónico',
      password: 'Contraseña Temporal',
      role: 'Rol de Usuario',
      roleUser: 'Cliente Estándar',
      roleAdmin: 'Administrador',
      submitCreate: 'Crear Usuario',
      totalUsers: 'Usuarios registrados',
      colName: 'Nombre',
      colEmail: 'Correo',
      colRole: 'Rol',
      colActions: 'Acciones',
      deleteUserPrompt: '¿Desea eliminar este usuario? Esta acción no se puede deshacer.',
      userDeleted: 'Usuario eliminado correctamente.',
      userCreated: 'Usuario creado con éxito.',
    },
    profile: {
      title: 'Mi Perfil',
      subtitle: 'Información de su cuenta y preferencias de huésped.',
      memberSince: 'Miembro de Arenal Kioro Suites',
      roleLabel: 'Tipo de Cuenta',
      statusActive: 'Cuenta Activa',
      changePassword: 'Para modificar sus datos o solicitar acceso especial, contacte a recepción.',
    },
    footer: {
      brand: 'Arenal Kioro Suites',
      subtitle: 'Hotel Boutique & Restaurant',
      tagline: 'Hospitalidad de clase mundial, gastronomía de autor y momentos inolvidables en un entorno exclusivo.',
      contactTitle: 'Contacto & Concierge',
      socialTitle: 'Síguenos en Redes',
      whatsappText: 'WhatsApp Directo',
      phone: '+506 8888-8888',
      email: 'reservas@arenalkioro.com',
      address: 'Boulevard Luxury 108, Costa Rica',
      rights: '© 2026 Arenal Kioro Suites Hotel Boutique & Restaurant. Todos los derechos reservados.',
    },
    confirmation: {
      kicker: 'Confirmar acción',
      accept: 'Aceptar',
      cancel: 'Cancelar',
      processing: 'Procesando...',
      close: 'Cerrar ventana',
      logoutTitle: '¿Cerrar sesión?',
      logoutMessage: 'Tu sesión actual se cerrará y volverás a la pantalla de inicio de sesión.',
      cancelReservationTitle: '¿Cancelar esta reserva?',
      cancelReservationMessage: 'La reserva cambiará al estado Cancelada. Confirma si deseas continuar.',
      confirmReservationTitle: '¿Aceptar esta reserva?',
      confirmReservationMessage: 'La reserva cambiará al estado Confirmada. Confirma si deseas continuar.',
    },
    common: {
      loading: 'Cargando información...',
      error: 'Ha ocurrido un error inesperado.',
      retry: 'Reintentar',
      back: 'Volver',
      save: 'Guardar',
      close: 'Cerrar',
      all: 'Todos',
      hotel: 'Hotel',
      restaurant: 'Restaurante',
    },
  },
  en: {
    nav: {
      home: 'Home',
      login: 'Sign In',
      dashboard: 'Dashboard',
      reservations: 'Reservations',
      users: 'Users',
      reserve: 'Book Now',
      myReservations: 'My Bookings',
      profile: 'Profile',
      logout: 'Sign Out',
      adminBadge: 'Admin',
      clientBadge: 'Guest',
      brandSubtitle: 'Boutique Hotel & Restaurant',
      language: 'Language',
      activities: 'Activities',
    },
    activities: {
      eyebrow: 'EXPERIENCES & WORKSHOPS',
      title: 'Hotel Activities & Craft Courses',
      subtitle: 'Enrich your stay with recreational sports, wellness spa therapies, and exclusive craft workshops led by certified specialists.',
      costNote: 'Additional cost to the room reservation',
      quotaNote: 'Limited slots per session',
      whatsappNote: 'Direct contact with the person in charge',
      searchPlaceholder: 'Search activity, workshop, or instructor...',
      itemsFound: 'experiences with available slots',
      perPerson: 'person',
      duration: 'Duration',
      schedule: 'Schedule',
      slots: 'Slots',
      slotsLeft: 'available',
      slotsTotal: 'total',
      inChargeLabel: 'Person in charge',
      contactWhatsApp: 'Book with Instructor',
      noResultsTitle: 'No activities found',
      noResultsDesc: 'Try another search term or choose a different category.',
      viewAllBtn: 'View all experiences',
      exclusiveGuests: 'EXCLUSIVE BENEFIT',
      calloutTitle: 'Staying at ReservaPro?',
      calloutDesc: 'All activity and workshop charges can be seamlessly billed to your room folio.',
      viewCatalog: 'Explore Hotel Activities',
    },
    home: {
      eyebrow: 'Exclusivity & Fine Dining',
      heroTitle: 'Where serene comfort meets refined taste.',
      heroDesc: 'Unforgettable boutique stays, luxury suites, and signature gastronomy crafted for the most discerning palates.',
      reserveHotel: 'Book a Suite',
      reserveDining: 'Gourmet Table',
      viewDashboard: 'Go to Dashboard',
      servicesTitle: 'Our Experiences',
      hotelTitle: 'Luxury Suites',
      hotelDesc: 'Refined spaces designed with bespoke finishes, panoramic views, and ultimate comfort.',
      restaurantTitle: 'Signature Dining',
      restaurantDesc: 'Tasting menus crafted from fresh local produce paired with world-class wines.',
      featuresTitle: 'Excellence in Every Detail',
      feature1Title: '24/7 Concierge Service',
      feature1Desc: 'Dedicated assistance to curate every moment of your stay.',
      feature2Title: 'Award-Winning Gastronomy',
      feature2Desc: 'Renowned international chefs creating unique culinary journeys.',
      feature3Title: 'Privacy & Tranquility',
      feature3Desc: 'Quiet, sophisticated environments envisioned for profound relaxation.',
      statsSuites: 'Luxury Suites',
      statsStars: 'Michelin Stars',
      statsSatisfaction: 'Satisfaction',
      statsExperience: 'Years of Tradition',
      quote: '“True luxury is not ostentation, but the art of making every single moment unforgettable.”',
    },
    login: {
      title: 'Sign In',
      subtitle: 'Access your account to manage your reservations and exclusive services.',
      email: 'Email address',
      emailPlaceholder: 'guest@example.com',
      password: 'Password',
      passwordPlaceholder: '••••••••',
      submitBtn: 'Enter Portal',
      loadingBtn: 'Verifying...',
      demoTitle: 'Available Demo Accounts:',
      demoAdmin: 'Administrator (Full control)',
      demoClient: 'Guest (Reservation management)',
      demoFill: 'Use credential',
      errorInvalid: 'Invalid credentials. Please check your email and password.',
    },
    dashboard: {
      welcome: 'Welcome back,',
      subtitle: 'Executive overview of your stay and scheduled experiences.',
      adminTitle: 'Executive Control Panel',
      adminSubtitle: 'Global oversight of reservations, guests, and establishment metrics.',
      totalReservations: 'Total Bookings',
      hotelReservations: 'Suites / Hotel',
      diningReservations: 'Tables / Dining',
      pendingReservations: 'Pending',
      confirmedReservations: 'Confirmed',
      cancelledReservations: 'Cancelled',
      registeredUsers: 'Registered Users',
      quickActions: 'Quick Actions',
      newBooking: 'New Reservation',
      viewAllBookings: 'View All Bookings',
      manageUsers: 'Manage Users',
      recentActivity: 'Recent Activity',
      distributionByType: 'Service Distribution',
      statusOverview: 'Booking Statuses',
      noRecentActivity: 'No recent activity recorded.',
    },
    reservations: {
      title: 'My Bookings',
      subtitle: 'Review and manage the itinerary of your upcoming experiences.',
      adminTitle: 'Reservation Management',
      adminSubtitle: 'Supervision and confirmation of all guest requests.',
      createTitle: 'Create New Reservation',
      createSubtitle: 'Customize your stay or dinner in a few simple steps.',
      serviceType: 'Service Type',
      hotelOption: 'Hotel Suite',
      restaurantOption: 'Restaurant Table',
      date: 'Date',
      time: 'Time',
      guests: 'Number of Guests',
      notes: 'Special Requests / Notes',
      notesPlaceholder: 'Allergies, suite preferences, anniversary celebration...',
      submitCreate: 'Confirm Booking Request',
      creating: 'Processing booking...',
      filterAll: 'All',
      filterPending: 'Pending',
      filterConfirmed: 'Confirmed',
      filterCancelled: 'Cancelled',
      searchPlaceholder: 'Search by name, email or ID...',
      emptyTitle: 'No bookings found',
      emptyDesc: 'You currently have no reservations matching this criteria.',
      makeFirstBooking: 'Make a reservation now',
      statusPending: 'Awaiting confirmation',
      statusConfirmed: 'Confirmed',
      statusCancelled: 'Cancelled',
      confirmAction: 'Confirm',
      cancelAction: 'Cancel',
      deleteAction: 'Delete',
      confirmPrompt: 'Are you sure you want to cancel this booking?',
      successCreate: 'Reservation created successfully!',
      roomType: 'Suite Type',
      tableType: 'Table Setting',
    },
    users: {
      title: 'User Management',
      subtitle: 'Administration of access permissions, roles, and accounts.',
      createUserTitle: 'Register New User',
      name: 'Full Name',
      email: 'Email Address',
      password: 'Temporary Password',
      role: 'User Role',
      roleUser: 'Standard Guest',
      roleAdmin: 'Administrator',
      submitCreate: 'Create User',
      totalUsers: 'Registered users',
      colName: 'Name',
      colEmail: 'Email',
      colRole: 'Role',
      colActions: 'Actions',
      deleteUserPrompt: 'Do you wish to delete this user? This action cannot be undone.',
      userDeleted: 'User deleted successfully.',
      userCreated: 'User created successfully.',
    },
    profile: {
      title: 'My Profile',
      subtitle: 'Your account credentials and guest preferences.',
      memberSince: 'Arenal Kioro Suites Member',
      roleLabel: 'Account Type',
      statusActive: 'Active Account',
      changePassword: 'To update your information or request VIP perks, please contact reception.',
    },
    footer: {
      brand: 'Arenal Kioro Suites',
      subtitle: 'Boutique Hotel & Restaurant',
      tagline: 'World-class hospitality, signature gastronomy, and unforgettable moments in an exclusive haven.',
      contactTitle: 'Contact & Concierge',
      socialTitle: 'Follow Our Journey',
      whatsappText: 'Direct WhatsApp',
      phone: '+506 8888-8888',
      email: 'reservations@arenalkioro.com',
      address: '108 Luxury Boulevard, Costa Rica',
      rights: '© 2026 Arenal Kioro Suites Boutique Hotel & Restaurant. All rights reserved.',
    },
    confirmation: {
      kicker: 'Confirm action',
      accept: 'Accept',
      cancel: 'Cancel',
      processing: 'Processing...',
      close: 'Close dialog',
      logoutTitle: 'Sign out?',
      logoutMessage: 'Your current session will end and you will return to the sign-in page.',
      cancelReservationTitle: 'Cancel this booking?',
      cancelReservationMessage: 'The booking status will change to Cancelled. Confirm if you wish to continue.',
      confirmReservationTitle: 'Accept this booking?',
      confirmReservationMessage: 'The booking status will change to Confirmed. Confirm if you wish to continue.',
    },
    common: {
      loading: 'Loading information...',
      error: 'An unexpected error occurred.',
      retry: 'Retry',
      back: 'Back',
      save: 'Save',
      close: 'Close',
      all: 'All',
      hotel: 'Hotel',
      restaurant: 'Restaurant',
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      login: 'Connexion',
      dashboard: 'Tableau de bord',
      reservations: 'Réservations',
      users: 'Utilisateurs',
      reserve: 'Réserver',
      myReservations: 'Mes réservations',
      profile: 'Profil',
      logout: 'Déconnexion',
      adminBadge: 'Admin',
      clientBadge: 'Client',
      brandSubtitle: 'Hôtel Boutique & Restaurant',
      language: 'Langue',
      activities: 'Activités',
    },
    activities: {
      eyebrow: 'EXPÉRIENCES & ATELIERS',
      title: 'Activités de l’Hôtel & Cours d’Artisanat',
      subtitle: 'Enrichissez votre séjour avec des sports de loisirs, des soins de spa et des cours d’artisanat exclusifs animés par des experts.',
      costNote: 'Frais supplémentaires à la réservation de la chambre',
      quotaNote: 'Places limitées par séance',
      whatsappNote: 'Contact direct avec le responsable du cours',
      searchPlaceholder: 'Rechercher une activité ou un instructeur...',
      itemsFound: 'expériences disponibles',
      perPerson: 'personne',
      duration: 'Durée',
      schedule: 'Horaire',
      slots: 'Places',
      slotsLeft: 'disponibles',
      slotsTotal: 'totales',
      inChargeLabel: 'Personne en charge',
      contactWhatsApp: 'Réserver avec l’instructeur',
      noResultsTitle: 'Aucune activité trouvée',
      noResultsDesc: 'Essayez un autre terme de recherche ou changez de catégorie.',
      viewAllBtn: 'Voir toutes les expériences',
      exclusiveGuests: 'AVANTAGE EXCLUSIF',
      calloutTitle: 'Séjournez-vous à ReservaPro ?',
      calloutDesc: 'Tous les frais d’activités et d’ateliers peuvent être débités directement sur la note de votre chambre.',
      viewCatalog: 'Voir les activités',
    },
    home: {
      eyebrow: 'Exclusivité & Haute Gastronomie',
      heroTitle: 'Où le repos rencontre le raffinement.',
      heroDesc: 'Des séjours d’exception, des suites luxueuses et une haute cuisine conçue pour les palais les plus exigeants.',
      reserveHotel: 'Réserver une Suite',
      reserveDining: 'Table Gastronomique',
      viewDashboard: 'Mon Tableau de bord',
      servicesTitle: 'Nos Expériences',
      hotelTitle: 'Suites de Luxe',
      hotelDesc: 'Des espaces pensés avec des finitions nobles, vues panoramiques et confort absolu.',
      restaurantTitle: 'Gastronomie Signature',
      restaurantDesc: 'Des menus dégustation élaborés avec des produits frais du terroir et accords mets-vins.',
      featuresTitle: 'L’Excellence dans les Moindres Détails',
      feature1Title: 'Conciergerie 24/7',
      feature1Desc: 'Un service attentionné dédié à combler le moindre de vos désirs.',
      feature2Title: 'Cuisine Primée',
      feature2Desc: 'Des chefs de renommée internationale pour une odyssée culinaire inoubliable.',
      feature3Title: 'Intimité et Sérénité',
      feature3Desc: 'Des ambiances calmes et sophistiquées propices à une quiétude absolue.',
      statsSuites: 'Suites de Prestige',
      statsStars: 'Étoiles Michelin',
      statsSatisfaction: 'Satisfaction',
      statsExperience: 'Années de Tradition',
      quote: '« Le vrai luxe ne réside pas dans l’ostentation, mais dans l’art de rendre chaque instant inoubliable. »',
    },
    login: {
      title: 'Connexion',
      subtitle: 'Accédez à votre espace privilégié pour gérer vos réservations.',
      email: 'Adresse e-mail',
      emailPlaceholder: 'client@exemple.fr',
      password: 'Mot de passe',
      passwordPlaceholder: '••••••••',
      submitBtn: 'Accéder au portail',
      loadingBtn: 'Vérification...',
      demoTitle: 'Comptes de démonstration :',
      demoAdmin: 'Administrateur (Accès total)',
      demoClient: 'Client (Gestion des séjours)',
      demoFill: 'Utiliser ce compte',
      errorInvalid: 'Identifiants incorrects. Veuillez vérifier votre adresse e-mail et mot de passe.',
    },
    dashboard: {
      welcome: 'Bienvenue,',
      subtitle: 'Aperçu de vos séjours et expériences à venir.',
      adminTitle: 'Panneau de Contrôle Exécutif',
      adminSubtitle: 'Supervision des réservations, clients et statistiques de l’établissement.',
      totalReservations: 'Total Réservations',
      hotelReservations: 'Suites / Hôtel',
      diningReservations: 'Tables / Restaurant',
      pendingReservations: 'En attente',
      confirmedReservations: 'Confirmées',
      cancelledReservations: 'Annulées',
      registeredUsers: 'Utilisateurs Inscrits',
      quickActions: 'Actions Rapides',
      newBooking: 'Nouvelle Réservation',
      viewAllBookings: 'Toutes les Réservations',
      manageUsers: 'Gérer les Utilisateurs',
      recentActivity: 'Activité Récente',
      distributionByType: 'Répartition par Service',
      statusOverview: 'État des Réservations',
      noRecentActivity: 'Aucune activité récente enregistrée.',
    },
    reservations: {
      title: 'Mes Réservations',
      subtitle: 'Consultez et organisez vos prochaines expériences.',
      adminTitle: 'Gestion des Réservations',
      adminSubtitle: 'Validation et suivi des demandes des hôtes.',
      createTitle: 'Nouvelle Réservation',
      createSubtitle: 'Personnalisez votre séjour ou dîner en quelques instants.',
      serviceType: 'Type de Prestation',
      hotelOption: 'Suite d’Hôtel',
      restaurantOption: 'Table de Restaurant',
      date: 'Date',
      time: 'Heure',
      guests: 'Nombre de Personnes',
      notes: 'Demandes Particulières / Remarques',
      notesPlaceholder: 'Allergies alimentaires, vue souhaitée, anniversaire...',
      submitCreate: 'Confirmer la Demande',
      creating: 'Traitement en cours...',
      filterAll: 'Toutes',
      filterPending: 'En attente',
      filterConfirmed: 'Confirmées',
      filterCancelled: 'Annulées',
      searchPlaceholder: 'Rechercher par nom, email ou ID...',
      emptyTitle: 'Aucune réservation trouvée',
      emptyDesc: 'Vous n’avez aucune réservation correspondant à ces critères.',
      makeFirstBooking: 'Réserver dès maintenant',
      statusPending: 'En attente de validation',
      statusConfirmed: 'Confirmée',
      statusCancelled: 'Annulée',
      confirmAction: 'Confirmer',
      cancelAction: 'Annuler',
      deleteAction: 'Supprimer',
      confirmPrompt: 'Êtes-vous sûr de vouloir annuler cette réservation ?',
      successCreate: 'Réservation enregistrée avec succès !',
      roomType: 'Type de Suite',
      tableType: 'Emplacement de Table',
    },
    users: {
      title: 'Gestion des Utilisateurs',
      subtitle: 'Administration des accès, rôles et comptes utilisateurs.',
      createUserTitle: 'Inscrire un Nouvel Utilisateur',
      name: 'Nom Complet',
      email: 'Adresse E-mail',
      password: 'Mot de passe temporaire',
      role: 'Rôle Utilisateur',
      roleUser: 'Client Standard',
      roleAdmin: 'Administrateur',
      submitCreate: 'Créer l’Utilisateur',
      totalUsers: 'Utilisateurs enregistrés',
      colName: 'Nom',
      colEmail: 'E-mail',
      colRole: 'Rôle',
      colActions: 'Actions',
      deleteUserPrompt: 'Voulez-vous vraiment supprimer cet utilisateur ?',
      userDeleted: 'Utilisateur supprimé avec succès.',
      userCreated: 'Utilisateur créé avec succès.',
    },
    profile: {
      title: 'Mon Profil',
      subtitle: 'Informations de compte et préférences.',
      memberSince: 'Membre Arenal Kioro Suites',
      roleLabel: 'Type de Compte',
      statusActive: 'Compte Actif',
      changePassword: 'Pour modifier vos informations ou demander des privilèges, contactez la conciergerie.',
    },
    footer: {
      brand: 'Arenal Kioro Suites',
      subtitle: 'Hôtel Boutique & Restaurant',
      tagline: 'Hospitalité de classe mondiale, haute gastronomie et moments inoubliables dans un cadre d’exception.',
      contactTitle: 'Contact & Conciergerie',
      socialTitle: 'Suivez-nous',
      whatsappText: 'WhatsApp Direct',
      phone: '+506 8888-8888',
      email: 'reservations@arenalkioro.com',
      address: '108 Boulevard Luxury, Costa Rica',
      rights: '© 2026 Arenal Kioro Suites Hôtel Boutique & Restaurant. Tous droits réservés.',
    },
    confirmation: {
      kicker: 'Confirmer l’action',
      accept: 'Accepter',
      cancel: 'Annuler',
      processing: 'Traitement...',
      close: 'Fermer la fenêtre',
      logoutTitle: 'Se déconnecter ?',
      logoutMessage: 'Votre session actuelle sera fermée et vous retournerez à la page de connexion.',
      cancelReservationTitle: 'Annuler cette réservation ?',
      cancelReservationMessage: 'La réservation passera à l’état Annulée. Confirmez si vous souhaitez continuer.',
      confirmReservationTitle: 'Accepter cette réservation ?',
      confirmReservationMessage: 'La réservation passera à l’état Confirmée. Confirmez si vous souhaitez continuer.',
    },
    common: {
      loading: 'Chargement en cours...',
      error: 'Une erreur inattendue est survenue.',
      retry: 'Réessayer',
      back: 'Retour',
      save: 'Enregistrer',
      close: 'Fermer',
      all: 'Tous',
      hotel: 'Hôtel',
      restaurant: 'Restaurant',
    },
  },
  zh: {
    nav: {
      home: '首页',
      login: '登录系统',
      dashboard: '控制台',
      reservations: '预订管理',
      users: '用户管理',
      reserve: '立即预订',
      myReservations: '我的预订',
      profile: '个人资料',
      logout: '退出登录',
      adminBadge: '管理员',
      clientBadge: '尊贵宾客',
      brandSubtitle: '精品酒店 & 米其林餐厅',
      language: '语言选择',
      activities: '酒店活动 & 课程',
    },
    activities: {
      eyebrow: '尊享体验 · 手作工坊',
      title: '酒店专属活动 & 手工艺术大师课',
      subtitle: '尽享休闲运动、奢华水疗养生以及由专业导师悉心指导的传统手工艺术课程。',
      costNote: '房费之外的额外自选项目费用',
      quotaNote: '每场名额有限，敬请提前预约',
      whatsappNote: '直接联系各项活动专属负责人',
      searchPlaceholder: '搜索活动、课程或导师姓名...',
      itemsFound: '项正在开放预约的体验',
      perPerson: '人',
      duration: '体验时长',
      schedule: '开放时间',
      slots: '名额',
      slotsLeft: '个剩余名额',
      slotsTotal: '总名额',
      inChargeLabel: '活动专职负责人',
      contactWhatsApp: '联系导师预订席位',
      noResultsTitle: '未找到相关活动',
      noResultsDesc: '请尝试其他关键词或更换分类。',
      viewAllBtn: '查看全部体验项目',
      exclusiveGuests: '住客专属礼遇',
      calloutTitle: '正在下榻 ReservaPro？',
      calloutDesc: '所有活动与手工坊费用均可统一计入您的客房账单，尊享便捷结账服务。',
      viewCatalog: '探索专属活动',
    },
    home: {
      eyebrow: '尊贵专享 · 顶级美馔',
      heroTitle: '静谧奢华与非凡品味的完美融合。',
      heroDesc: '独一无二的精品套房与定制佳肴，专为追求卓越品质的尊贵宾客倾心打造。',
      reserveHotel: '预订奢华套房',
      reserveDining: '预订主厨餐桌',
      viewDashboard: '进入控制台',
      servicesTitle: '尊享体验',
      hotelTitle: '奢华精品套房',
      hotelDesc: '大师级设计风格，坐拥全景视野与极致舒适享受。',
      restaurantTitle: '主厨定制餐厅',
      restaurantDesc: '甄选当地当季新鲜食材，为您奉上令人回味的星级美味。',
      featuresTitle: '卓越体现在每个细节',
      feature1Title: '24小时专属管家',
      feature1Desc: '细致入微的管家式礼宾服务，悉心满足您的所有期许。',
      feature2Title: '屡获殊荣的美味',
      feature2Desc: '国际名厨联袂献礼，带来震撼味蕾的艺术料理。',
      feature3Title: '尊贵私密与宁静',
      feature3Desc: '静谧优雅的奢享环境，为您提供纯粹的放松时刻。',
      statsSuites: '顶级奢华套房',
      statsStars: '米其林星级',
      statsSatisfaction: '宾客满意度',
      statsExperience: '年传世积淀',
      quote: '“真正的奢华不在于炫耀，而在于将每一个平凡瞬间化为永恒回忆的艺术。”',
    },
    login: {
      title: '登录系统',
      subtitle: '登录您的专属账户以管理各项预订与尊贵服务。',
      email: '电子邮箱',
      emailPlaceholder: 'guest@example.com',
      password: '登录密码',
      passwordPlaceholder: '••••••••',
      submitBtn: '立即进入系统',
      loadingBtn: '正在验证...',
      demoTitle: '可用测试账户：',
      demoAdmin: '系统管理员（全部权限）',
      demoClient: '尊贵宾客（预订与查询）',
      demoFill: '一键填入',
      errorInvalid: '登录凭证无效，请核对您的邮箱与密码。',
    },
    dashboard: {
      welcome: '欢迎归来，',
      subtitle: '您的奢享行程与服务安排概览。',
      adminTitle: '综合管理控制台',
      adminSubtitle: '全局监控酒店预订、餐厅安排及运营数据指标。',
      totalReservations: '预订总数',
      hotelReservations: '酒店套房',
      diningReservations: '餐厅席位',
      pendingReservations: '待确认',
      confirmedReservations: '已确认',
      cancelledReservations: '已取消',
      registeredUsers: '注册宾客数',
      quickActions: '快捷操作',
      newBooking: '新增预订',
      viewAllBookings: '查看所有预订',
      manageUsers: '用户权限管理',
      recentActivity: '近期动态',
      distributionByType: '服务类型占比',
      statusOverview: '预订状态分布',
      noRecentActivity: '暂无近期预订动态。',
    },
    reservations: {
      title: '我的预订',
      subtitle: '查看并管理您接下来的所有尊享行程。',
      adminTitle: '预订总控系统',
      adminSubtitle: '审核与安排所有宾客的入住与就餐申请。',
      createTitle: '创建新预订',
      createSubtitle: '轻松定制您的入住套房或星级盛宴。',
      serviceType: '服务类型',
      hotelOption: '精品酒店套房',
      restaurantOption: '米其林餐厅席位',
      date: '预订日期',
      time: '预订时间',
      guests: '就餐/入住人数',
      notes: '特别需求与备注',
      notesPlaceholder: '饮食过敏源、楼层偏好、纪念日布置需求等...',
      submitCreate: '确认提交预订',
      creating: '正在提交中...',
      filterAll: '全部',
      filterPending: '待确认',
      filterConfirmed: '已确认',
      filterCancelled: '已取消',
      searchPlaceholder: '通过姓名、邮箱或订单号搜索...',
      emptyTitle: '未找到相关预订',
      emptyDesc: '当前筛选条件下暂无预订记录。',
      makeFirstBooking: '立即发起新的预订',
      statusPending: '等待确认中',
      statusConfirmed: '已确认安排',
      statusCancelled: '已取消',
      confirmAction: '确认预订',
      cancelAction: '取消预订',
      deleteAction: '删除记录',
      confirmPrompt: '确定要取消这笔预订吗？',
      successCreate: '预订申请已成功提交！',
      roomType: '套房房型',
      tableType: '餐桌位置',
    },
    users: {
      title: '系统用户管理',
      subtitle: '管理系统账户权限、角色及登录凭证。',
      createUserTitle: '注册新用户',
      name: '姓名',
      email: '电子邮箱',
      password: '初始密码',
      role: '用户角色',
      roleUser: '标准宾客',
      roleAdmin: '系统管理员',
      submitCreate: '确认创建',
      totalUsers: '已注册用户总数',
      colName: '姓名',
      colEmail: '电子邮箱',
      colRole: '角色权限',
      colActions: '操作',
      deleteUserPrompt: '确定要删除此用户吗？此操作不可撤销。',
      userDeleted: '用户已成功删除。',
      userCreated: '新用户已成功创建。',
    },
    profile: {
      title: '个人中心',
      subtitle: '查看您的账户资料与偏好设置。',
      memberSince: 'Arenal Kioro Suites 尊享会员',
      roleLabel: '账户权限',
      statusActive: '正常可用',
      changePassword: '如需修改资料或升级贵宾特权，请直接联系大堂礼宾前台。',
    },
    footer: {
      brand: 'Arenal Kioro Suites',
      subtitle: '精品酒店 & 米其林餐厅',
      tagline: '世界顶级的下榻体验与星级珍馐美馔，为您缔造难以忘怀的尊崇时刻。',
      contactTitle: '尊享礼宾 & 预约专线',
      socialTitle: '官方社交媒体',
      whatsappText: 'WhatsApp 专属在线客服',
      phone: '+506 8888-8888',
      email: 'reservations@arenalkioro.com',
      address: '哥斯达黎加 奢华大道 108 号',
      rights: '© 2026 Arenal Kioro Suites 奢华精品酒店 & 米其林餐厅 版权所有。',
    },
    confirmation: {
      kicker: '确认操作',
      accept: '确认',
      cancel: '取消',
      processing: '处理中...',
      close: '关闭窗口',
      logoutTitle: '退出登录？',
      logoutMessage: '当前会话将结束，您将返回登录页面。',
      cancelReservationTitle: '取消此预订？',
      cancelReservationMessage: '预订状态将更改为已取消。请确认是否继续。',
      confirmReservationTitle: '接受此预订？',
      confirmReservationMessage: '预订状态将更改为已确认。请确认是否继续。',
    },
    common: {
      loading: '正在加载数据...',
      error: '发生意外错误，请稍后重试。',
      retry: '重新尝试',
      back: '返回',
      save: '保存',
      close: '关闭',
      all: '全部',
      hotel: '酒店',
      restaurant: '餐厅',
    },
  },
};

export const languages = [
  { code: 'es', label: 'Español', flag: '🇪🇸', short: 'ES' },
  { code: 'en', label: 'English', flag: '🇬🇧', short: 'EN' },
  { code: 'fr', label: 'Français', flag: '🇫🇷', short: 'FR' },
  { code: 'zh', label: '中文', flag: '🇨🇳', short: 'ZH' },
];

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('arenalkioro_lang') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('arenalkioro_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (path, fallback = '') => {
    const keys = path.split('.');
    let current = translations[lang];

    for (const key of keys) {
      if (current && current[key] !== undefined) {
        current = current[key];
      } else {
        // Fallback to Spanish if missing
        let fallbackVal = translations.es;
        for (const fKey of keys) {
          if (fallbackVal && fallbackVal[fKey] !== undefined) {
            fallbackVal = fallbackVal[fKey];
          } else {
            return fallback || path;
          }
        }
        return fallbackVal;
      }
    }
    return current;
  };

  const currentLanguage = languages.find((l) => l.code === lang) || languages[0];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
